### ISSUE TITLE
Needs to be replaced by our own fedberry-logos package at some point in future

### ISSUE THREAD

**Issue by agrez** [fedberry/fedberry-logos#1]

**Comment by agrez** [comment]
Do we have an svg file of our logo floating around somewhere?

**Comment by Gormartsen** [comment]
Will upload soon

**Comment by Gormartsen** [comment]
Here: https://github.com/fedberry/fedberry.github.io/tree/master/logo

But eps file is original from shutter stock. 

I don't have vector editor here to properly modify it now.

**Comment by agrez** [comment]
Thanks! I was just chasing some type of vector format really, so eps is all good.

**Comment by agrez** [comment]
ooops! I'm getting trigger happy.....

**Comment by Gormartsen** [comment]
eps file need to be updated with selected colours and "company name" text need to be removed.

**Comment by agrez** [comment]
This is done. Rpms are in the 24 repos.
